Avoid unnecessary operations if Vec<Asset> is empty
metaplex-foundation/digital-asset-rpc-infrastructure pull request #229
Opened 2024-12-09 10:13 UTC by AhzamAkhtar

- [x] Avoid unnecessary operation calls if **assets** vector is empty.

2024-12-09 13:09 UTC, Nagaprasadvr requested changes

2024-12-09 13:09 UTC, Nagaprasadvr commented on digital_asset_types/src/dapi/common/asset.rs
> +    let base_asset_list = AssetList {
can we move this check inside asset_list_to_rpc ?

2024-12-31 01:20 UTC, danenbm approved these changes

2024-12-31 01:20 UTC, danenbm commented on digital_asset_types/src/dapi/common/asset.rs
> +        page : page.map(|x| x as u32),
NIt: whitespace

2025-01-11 01:40 UTC, danenbm approved these changes

2025-01-13 11:32 UTC, closed without merging

2025-01-13 11:32 UTC, kespinola commented
There are no async calls as a result of rpc transform so I'm going to close this issue. If introduced in the future should have a benchmark to note time/utilization improvement.